# Generated by Django 6.0.4 on 2026-05-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cost_prince",
            new_name="cost_price",
        ),
    ]
